services:
  - type: web
    name: medusa-backend
    runtime: node
    rootDir: my-medusa-store
    plan: free
    buildCommand: corepack enable && corepack prepare yarn@1.22.19 --activate && yarn install --frozen-lockfile && yarn build
    startCommand: ./scripts/init-production.sh && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_ax28ZfsovVqm@ep-blue-resonance-abxztqnk-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require
      - key: REDIS_URL
        value: redis://default:AZloAAIncDE3YjgxYThjNGFkODE0MjNiYTU2YWI4OGZmYzY5NTgwOXAxMzkyNzI@endless-weevil-39272.upstash.io:6379
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this
      - key: COOKIE_SECRET
        value: your-super-secret-cookie-key-change-this
      - key: STORE_CORS
        value: https://medusa-frontend-w382.onrender.com
      - key: ADMIN_CORS
        value: https://medusa-frontend-w382.onrender.com
      - key: AUTH_CORS
        value: https://medusa-frontend-w382.onrender.com
      - key: MEDUSA_ADMIN_CORS
        value: https://medusa-frontend-w382.onrender.com
      - key: MEDUSA_STORE_CORS
        value: https://medusa-frontend-w382.onrender.com
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: default
      - key: MEDUSA_ADMIN_ONBOARDING_FLOW
        value: default
  
  - type: web
    name: medusa-frontend
    runtime: node
    rootDir: my-medusa-storefront
    plan: free
    buildCommand: corepack enable && corepack prepare yarn@1.22.19 --activate && yarn install --frozen-lockfile && yarn build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: NEXT_PUBLIC_API_URL
        value: https://medusa-backend-8c7e.onrender.com
      - key: NEXT_PUBLIC_MEDUSA_BACKEND_URL
        value: https://medusa-backend-8c7e.onrender.com
      - key: MEDUSA_BACKEND_URL
        value: https://medusa-backend-8c7e.onrender.com
      - key: NEXT_PUBLIC_STORE_CORS
        value: https://medusa-frontend-w382.onrender.com
      - key: NEXT_PUBLIC_ADMIN_CORS
        value: https://medusa-frontend-w382.onrender.com
      - key: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
        value: pk_01234567890abcdef
      - key: NEXT_PUBLIC_BASE_URL
        value: https://medusa-frontend-w382.onrender.com
      - key: HOSTNAME
        value: 0.0.0.0

  # Nota: Crear PostgreSQL y Redis manualmente en Render Dashboard
  # Luego reemplazar las URLs arriba con las URLs reales
    